
#include <stdio.h>
#include <stdint.h>
#include <string.h>
#include <ctype.h>

int main(int argc, char **argv)
{
	FILE *in, *out;
	uint32_t magic, ofs_table, len_table;
	uint32_t i, num_files;

	if (argc != 3)
	{
		printf("usage: %s pak0.pak pak0.pak.h\n", argv[0]);
		return 0;
	}

	in = fopen(argv[1], "rb");

	fread(&magic, sizeof(uint32_t), 1, in);
	fread(&ofs_table, sizeof(uint32_t), 1, in);
	fread(&len_table, sizeof(uint32_t), 1, in);

	if (memcmp(&magic, "PACK", 4) != 0)
	{
		fclose(in);
		printf("%s is not a valid pak file\n", argv[1]);
		return 1;
	}

	fseek(in, ofs_table, SEEK_SET);

	num_files = len_table / 64;

	out = fopen(argv[2], "w");

	fprintf(out, "// generated by pak2rom\n");
	fprintf(out, "#include <stdint.h>\n\n");
	fprintf(out, "static const uint8_t zip[] = {\n");
	fprintf(out, "#embed \"%s\"\n", argv[1]);
	fprintf(out, "};\n\n");
	fprintf(out, "static struct {\n");
	fprintf(out, "\tconst char *path;\n");
	fprintf(out, "\tconst uint8_t *ptr;\n");
	fprintf(out, "\tconst size_t size;\n");
	fprintf(out, "} zip_dir[] = {\n");

	for (i = 0; i < num_files; i++)
	{
		char filename[56];
		uint32_t ofs, len;

		fread(filename, sizeof(filename), 1, in);
		fread(&ofs, sizeof(uint32_t), 1, in);
		fread(&len, sizeof(uint32_t), 1, in);

		printf("file %u: %s at offset %u\n", i, filename, ofs);

		fprintf(out, "\t{ \"%s\", zip + %u, %u },\n", filename, ofs, len);
	}

	fprintf(out, "\t{ NULL, NULL, 0 }\n");
	fprintf(out, "};\n\n");
	fprintf(out, "static const size_t zip_dir_num_files = %u;\n", num_files);

	fclose(in);
	fclose(out);

	return 0;
}
