
#include "miniz.c"

#include <ctype.h>

int main(int argc, char **argv)
{
	FILE *out;
	mz_uint i, num_files, actual_num_files;
	mz_zip_archive zip;

	if (argc != 3)
	{
		printf("usage: %s pak.pk3 pak.pk3.c\n", argv[0]);
		return 0;
	}

	memset(&zip, 0, sizeof(zip));

	if (!mz_zip_reader_init_file(&zip, argv[1], 0))
	{
		printf("%s\n", mz_zip_get_error_string(zip.m_last_error));
	}

	out = fopen(argv[2], "w");

	num_files = mz_zip_reader_get_num_files(&zip);

	// printf("num_files: %u\n", num_files);

	fprintf(out, "// generated by zip2rom\n");
	fprintf(out, "#include <stdint.h>\n\n");
	fprintf(out, "static const uint8_t zip[] = {\n");
	fprintf(out, "#embed \"%s\"\n", argv[1]);
	fprintf(out, "};\n\n");
	fprintf(out, "static struct {\n");
	fprintf(out, "\tconst char *path;\n");
	fprintf(out, "\tconst uint8_t *ptr;\n");
	fprintf(out, "\tconst size_t size;\n");
	fprintf(out, "} zip_dir[] = {\n");

	actual_num_files = 0;
	for (i = 0; i < num_files; i++)
	{
		char filename[MZ_ZIP_MAX_ARCHIVE_FILENAME_SIZE];
		mz_zip_archive_file_stat stat;

		if (mz_zip_reader_is_file_a_directory(&zip, i))
			continue;

		mz_zip_reader_file_stat(&zip, i, &stat);

		strncpy(filename, stat.m_filename, sizeof(filename));

		for (size_t j = 0; filename[j]; j++){
			filename[j] = tolower(filename[j]);
		}

		printf("file %u: %s at offset %u\n", actual_num_files, filename, stat.m_local_header_ofs + stat.m_comment_size + strlen(stat.m_filename) + 30);

		fprintf(out, "\t{ \"%s\", zip + %u, %u },\n", filename, stat.m_local_header_ofs + stat.m_comment_size + strlen(stat.m_filename) + 30, stat.m_uncomp_size);

		actual_num_files++;
	}

	fprintf(out, "\t{ NULL, NULL, 0 }\n");
	fprintf(out, "};\n\n");
	fprintf(out, "static const size_t zip_dir_num_files = %u;\n", actual_num_files);

	mz_zip_reader_end(&zip);

	fclose(out);

	return 0;
}
