// generated by zip2rom
#include <stdint.h>

static const uint8_t zip[] = {
#embed "dreamcasko.pk3"
};

static struct {
	const char *path;
	const uint8_t *ptr;
	const size_t size;
} zip_dir[] = {
	{ "models/dreamcasko.iqm", zip + 88, 109324 },
	{ "models/dreamcasko.md3", zip + 109463, 42332 },
	{ "textures/models/dreamcasko/body.pvr", zip + 152002, 8208 },
	{ "textures/models/dreamcasko/clothing.pvr", zip + 160279, 8208 },
	{ "textures/models/dreamcasko/face.pvr", zip + 168552, 8208 },
	{ NULL, NULL, 0 }
};

static const size_t zip_dir_num_files = 5;
