// generated by zip2rom
#include <stdint.h>

static const uint8_t zip[] = {
#embed "trade-federation-ship.pk3"
};

static struct {
	const char *path;
	const uint8_t *ptr;
	const size_t size;
} zip_dir[] = {
	{ "maps/trade-federation-ship.bsp", zip + 95, 332784 },
	{ "models/dreamcasko.iqm", zip + 332967, 109324 },
	{ "models/dreamcasko.md3", zip + 442342, 42332 },
	{ "textures/dev/blue001a.pvr", zip + 484811, 6160 },
	{ "textures/dev/blue001b.pvr", zip + 491026, 6160 },
	{ "textures/dev/grey001a.pvr", zip + 497241, 6160 },
	{ "textures/dev/grey002a.pvr", zip + 503456, 6160 },
	{ "textures/dev/orange001a.pvr", zip + 509673, 6160 },
	{ "textures/dev/orange002a.pvr", zip + 515890, 6160 },
	{ "textures/dev/orange002b.pvr", zip + 522107, 6160 },
	{ "textures/dev/red001a.pvr", zip + 528321, 6160 },
	{ "textures/dev/red001b.pvr", zip + 534535, 6160 },
	{ "textures/dev/ref_10.pvr", zip + 540748, 6160 },
	{ "textures/dev/ref_10a.pvr", zip + 546962, 6160 },
	{ "textures/dev/ref_20.pvr", zip + 553175, 6160 },
	{ "textures/dev/ref_20a.pvr", zip + 559389, 6160 },
	{ "textures/dev/ref_30.pvr", zip + 565602, 6160 },
	{ "textures/dev/ref_30a.pvr", zip + 571816, 6160 },
	{ "textures/dev/ref_40.pvr", zip + 578029, 6160 },
	{ "textures/dev/ref_40a.pvr", zip + 584243, 6160 },
	{ "textures/dev/ref_50.pvr", zip + 590456, 6160 },
	{ "textures/dev/ref_50a.pvr", zip + 596670, 6160 },
	{ "textures/dev/ref_60.pvr", zip + 602883, 6160 },
	{ "textures/dev/ref_60a.pvr", zip + 609097, 6160 },
	{ "textures/dev/ref_70.pvr", zip + 615310, 6160 },
	{ "textures/dev/ref_70a.pvr", zip + 621524, 6160 },
	{ "textures/dev/ref_80.pvr", zip + 627737, 6160 },
	{ "textures/dev/ref_80a.pvr", zip + 633951, 6160 },
	{ "textures/dev/ref_90.pvr", zip + 640164, 6160 },
	{ "textures/dev/ref_90a.pvr", zip + 646378, 6160 },
	{ "textures/models/dreamcasko/body.pvr", zip + 652706, 8208 },
	{ "textures/models/dreamcasko/clothing.pvr", zip + 660983, 8208 },
	{ "textures/models/dreamcasko/face.pvr", zip + 669256, 8208 },
	{ NULL, NULL, 0 }
};

static const size_t zip_dir_num_files = 33;
