// generated by zip2rom
#include <stdint.h>

static const uint8_t zip[] = {
#embed "trade-federation-ship.pk3"
};

static struct {
	const char *path;
	const uint8_t *ptr;
	const size_t size;
} zip_dir[] = {
	{ "maps/trade-federation-ship.bsp", zip + 95, 332784 },
	{ "textures/dev/blue001a.pvr", zip + 333016, 6160 },
	{ "textures/dev/blue001b.pvr", zip + 339231, 6160 },
	{ "textures/dev/grey001a.pvr", zip + 345446, 6160 },
	{ "textures/dev/grey002a.pvr", zip + 351661, 6160 },
	{ "textures/dev/orange001a.pvr", zip + 357878, 6160 },
	{ "textures/dev/orange002a.pvr", zip + 364095, 6160 },
	{ "textures/dev/orange002b.pvr", zip + 370312, 6160 },
	{ "textures/dev/red001a.pvr", zip + 376526, 6160 },
	{ "textures/dev/red001b.pvr", zip + 382740, 6160 },
	{ "textures/dev/ref_10.pvr", zip + 388953, 6160 },
	{ "textures/dev/ref_10a.pvr", zip + 395167, 6160 },
	{ "textures/dev/ref_20.pvr", zip + 401380, 6160 },
	{ "textures/dev/ref_20a.pvr", zip + 407594, 6160 },
	{ "textures/dev/ref_30.pvr", zip + 413807, 6160 },
	{ "textures/dev/ref_30a.pvr", zip + 420021, 6160 },
	{ "textures/dev/ref_40.pvr", zip + 426234, 6160 },
	{ "textures/dev/ref_40a.pvr", zip + 432448, 6160 },
	{ "textures/dev/ref_50.pvr", zip + 438661, 6160 },
	{ "textures/dev/ref_50a.pvr", zip + 444875, 6160 },
	{ "textures/dev/ref_60.pvr", zip + 451088, 6160 },
	{ "textures/dev/ref_60a.pvr", zip + 457302, 6160 },
	{ "textures/dev/ref_70.pvr", zip + 463515, 6160 },
	{ "textures/dev/ref_70a.pvr", zip + 469729, 6160 },
	{ "textures/dev/ref_80.pvr", zip + 475942, 6160 },
	{ "textures/dev/ref_80a.pvr", zip + 482156, 6160 },
	{ "textures/dev/ref_90.pvr", zip + 488369, 6160 },
	{ "textures/dev/ref_90a.pvr", zip + 494583, 6160 },
	{ NULL, NULL, 0 }
};

static const size_t zip_dir_num_files = 28;
